name: Build and Push to GHCR


permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}/
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sarp
      TAG: latest
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}
      COMMIT: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Compose Services
        run: docker compose build
  
      - name: Tag Docker Image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.IMAGE_NAME }}:${{ env.COMMIT }}

      - name: List all Docker Images
        run: docker images

      - name: Push Docker Image to GHCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.COMMIT }}

