name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          echo "DOCKER_REGISTRY=ghcr.io/${{ github.repository_owner }}/" >> $GITHUB_ENV
          echo "IMAGE_NAME=${DOCKER_REGISTRY}sarp" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Compose Services
        run: docker compose build
        env:
          DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
          TAG: "latest"

      - name: Tag Docker Image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TIMESTAMP
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_HASH
          
      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TIMESTAMP
          docker push $IMAGE_NAME:$COMMIT_HASH

