name: Build and Push to GHCR


permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src
    env:
      DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}/
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sarp
      TAG: latest
      TIMESTAMP: $(date +%Y%m%d%H%M%S)
      COMMIT: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Compose Services
        run: docker compose build
  
      - name: Tag Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:$TIMESTAMP
          docker tag $IMAGE_NAME:${{ env.TAG }} $IMAGE_NAME:$COMMIT

      - name: List all Docker Images
        run: docker images

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME:${{ env.TAG }}
          docker push $IMAGE_NAME:$TIMESTAMP
          docker push $IMAGE_NAME:$COMMIT

